apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: gpu-a10g
spec:
  nodeLabels:
    workload: gpu
  nodeTaints:
    - key: nvidia.com/gpu
      value: "true"
      effect: NoSchedule
